### PR TITLE
fix download

### PR DESCRIPTION
**Pull request by mathause**
This is an attempt to fix the downloads. I saw too late that you already started implementing this with a callback. In any case this is only a WIP & it does not return the geojeson of the _selected_ polygons.

Also I am not sure how many nested levels of `<div>` this is now nested.

### CODE REVIEW

**Comment by mathause** [comment]
I just tried your `dl_netcdf` callback and that seems to work as well (when replacing `f"./data/{file_name}.nc"` with `f"{DATA_DIR}/{file_name}.nc"`). However, this is _much_ slower than with a direct download (as implemented here). Maybe because with `send_file` the file gets first before opening the "Save As" dialogue.

**Comment by mathause** [comment]
Ah yes I mostly wanted to play around with dash a bit - so I am also fine with just closing this PR again.

**Comment by romatt** [comment]
Oh no, I´ve already implemented both the NetCDF and GeoJSON downloader in the latest feature branch! I will compare with your solution and maybe I can combine the two solutions. The only issue I currently still have is that the /data/ directory will get flooded with geojson files whenever filters are changed - gotta change that so that a file is only ever generated when someone clicks on download.

**Comment by mathause** [comment]
No worries. This was just a good exercise to try out dash and understand it a bit better.

**Pull request closed without merging**
